### ISSUE TITLE
Matryoshka: What's the 4020/5015 motor for at the top?

### ISSUE THREAD

**Issue by eduncan911** [Greg191134/Voron#4]
In the Matryoshka option, you show the two 4010 motors on each side.  Check.

However, there's still the top 4020 motor (or 5015 if upgrading) at the top.  What is this for?

Tried looking at various STLs and images, and I don't see an outlet for this.

**Comment by reparator** [comment]
Same question from me:
Is the upper cooling fan obsolete?

**Comment by eduncan911** [comment]
As far as I can tell, the Afterburner fan at the top does nothing.  There are no vents from the top down.  If you look at the Tool head front STLs, it's completely blocked off at the top - where normally the 4020 or 5015 AB fan would blow through normal AB designs. 

So essentially it's dead weight.  Just for looks maybe?

The top AB fan looks like it can be removed completely with this mod, saving some weight.

https://github.com/Greg191134/Voron/blob/master/Afterburner%20Optimisation/The%20Matryoshka/Toolhead%20cartridge%20front%20-%20Mosquito.stl

**Comment by eduncan911** [comment]
After looking at the CAD a bit more, I'm guessing the 5015/4020 of the after burner is left there for compatibility with tool swaps.  So, you can swap in another hotend/fan duct, and have the 5015/4020 available for part cooling.

But when using the Matryoshka, you just leave the 5015/4020 disconnected, and connect the part cooling JST to the 4010s.

IOW, the 5015 is deadweight.
